// templates.js - All 26 HR document templates for Padaria Villas Garden
const fs = require('fs');
const path = require('path');

const EMPRESA = {
  nome: 'PADARIA E CONFEITARIA VILLAS GARDEN LTDA.',
  endereco: 'Av. 28 de Setembro, Lojas 253 e 255 - Vila Isabel',
  cep: '20551-031',
  cidade: 'Rio de Janeiro',
  uf: 'RJ',
  cnpj: '02.113.776/0001-43',
  ie: '86.184.540'
};

function getLogoBase64() {
  try {
    const logoPath = path.join(__dirname, 'public', 'logo.jpg');
    return fs.readFileSync(logoPath).toString('base64');
  } catch (e) {
    console.error('Logo not found:', e.message);
    return null;
  }
}

// Template body uses markers:
// {{field}} = employee field
// [[key]] = custom field value
// # text = section header
// --- = separator line
// [EMPLOYEE_INFO] = formatted employee data block
// [SIGNATURES:n] = signature area with n signatures
// [DATE_LINE] = date/location line

const TEMPLATES = [
  // ═══ ADMISSÃO ═══
  {
    id: 'ficha-registro',
    title: 'FICHA DE REGISTRO DE EMPREGADO',
    category: 'admissao',
    categoryLabel: 'Admissão',
    icon: '📋',
    customFields: [],
    body: [
      '# DADOS PESSOAIS',
      'Nome: {{nome}}',
      'CPF: {{cpf}} | RG: {{rg}} - {{orgaoEmissor}}',
      'Data de Nascimento: {{dataNascimento}} | Sexo: {{sexo}}',
      'Estado Civil: {{estadoCivil}} | Nacionalidade: {{nacionalidade}}',
      'Naturalidade: {{naturalidade}}',
      'Nome da Mãe: {{nomeMae}}',
      'Nome do Pai: {{nomePai}}',
      '---',
      '# ENDEREÇO',
      '{{endereco}}, {{numero}} {{complemento}}',
      'Bairro: {{bairro}} | Cidade: {{cidade}} - {{estado}}',
      'CEP: {{cep}} | Telefone: {{telefone}} | Celular: {{celular}}',
      'E-mail: {{email}}',
      '---',
      '# DOCUMENTOS',
      'CTPS: {{ctpsNumero}} Série: {{ctpsSerie}} UF: {{ctpsUf}}',
      'PIS/PASEP: {{pisPasep}}',
      'Título de Eleitor: {{tituloEleitor}} Zona: {{zonaEleitoral}} Seção: {{secaoEleitoral}}',
      'Cert. Reservista: {{reservista}}',
      'CNH: {{cnhNumero}} Cat.: {{cnhCategoria}} Val.: {{cnhValidade}}',
      '---',
      '# DADOS PROFISSIONAIS',
      'Cargo: {{cargo}} | Departamento: {{departamento}}',
      'Data de Admissão: {{dataAdmissao}} | Salário: R$ {{salario}}',
      'Tipo de Contrato: {{tipoContrato}} | Jornada: {{jornadaTrabalho}}',
      'Escolaridade: {{escolaridade}}',
      '---',
      '# DADOS BANCÁRIOS',
      'Banco: {{banco}} | Agência: {{agencia}} | Conta: {{conta}} ({{tipoConta}})',
      'Chave PIX: {{chavePix}}',
      '---',
      '# SAÚDE E EMERGÊNCIA',
      'Tipo Sanguíneo: {{tipoSanguineo}} | Alergias: {{alergias}}',
      'Contato de Emergência: {{contatoEmergencia}} - {{telEmergencia}}',
      '---',
      '# DEPENDENTES',
      '{{dependentes}}',
      '[SIGNATURES:2]',
    ]
  },
  {
    id: 'contrato-trabalho',
    title: 'CONTRATO DE TRABALHO',
    category: 'admissao',
    categoryLabel: 'Admissão',
    icon: '📋',
    customFields: [
      {key: 'periodo_experiencia', label: 'Período de Experiência (dias)', type: 'text', default: '45'},
      {key: 'horario_trabalho', label: 'Horário de Trabalho', type: 'text', default: '06:00 às 14:20'},
      {key: 'dia_pagamento', label: 'Dia do Pagamento', type: 'text', default: '5º dia útil'},
    ],
    body: [
      'Pelo presente instrumento particular de Contrato de Trabalho por Prazo Determinado, que entre si fazem, de um lado ' + EMPRESA.nome + ', inscrita no CNPJ sob nº ' + EMPRESA.cnpj + ', com sede na ' + EMPRESA.endereco + ', ' + EMPRESA.cidade + '/' + EMPRESA.uf + ', CEP ' + EMPRESA.cep + ', doravante denominada EMPREGADORA, e de outro lado:',
      '---',
      '[EMPLOYEE_INFO]',
      '---',
      'Doravante denominado(a) EMPREGADO(A), têm entre si justo e contratado o seguinte:',
      '',
      '# CLÁUSULA 1ª - DA FUNÇÃO',
      'O(A) EMPREGADO(A) é admitido(a) para exercer a função de {{cargo}}, no departamento de {{departamento}}, obrigando-se a executar as tarefas inerentes à função.',
      '',
      '# CLÁUSULA 2ª - DA REMUNERAÇÃO',
      'O(A) EMPREGADO(A) receberá a remuneração mensal de R$ {{salario}} ({{salario}} reais), pagável até o [[dia_pagamento]] subsequente ao mês vencido.',
      '',
      '# CLÁUSULA 3ª - DA JORNADA',
      'A jornada de trabalho será de [[horario_trabalho]], com intervalo para refeição/descanso conforme legislação vigente, de segunda a sábado, com folga semanal.',
      '',
      '# CLÁUSULA 4ª - DO PRAZO',
      'O presente contrato é celebrado por prazo determinado de [[periodo_experiencia]] dias a título de experiência, podendo ser prorrogado uma vez, respeitado o limite de 90 dias.',
      '',
      '# CLÁUSULA 5ª - DAS OBRIGAÇÕES',
      'O(A) EMPREGADO(A) se compromete a: cumprir o regulamento interno da empresa; manter sigilo sobre informações da empresa; zelar pelo patrimônio e equipamentos; cumprir as normas de higiene e segurança do trabalho; usar corretamente os uniformes e EPIs fornecidos.',
      '',
      '# CLÁUSULA 6ª - DA RESCISÃO',
      'O presente contrato poderá ser rescindido a qualquer tempo, por qualquer das partes, nas formas previstas na CLT.',
      '',
      'E, por estarem de pleno acordo, as partes assinam o presente em 2 (duas) vias de igual teor.',
      '[DATE_LINE]',
      '[SIGNATURES:2]',
    ]
  },
  {
    id: 'vale-transporte',
    title: 'DECLARAÇÃO DE OPÇÃO PELO VALE-TRANSPORTE',
    category: 'admissao',
    categoryLabel: 'Admissão',
    icon: '📋',
    customFields: [
      {key: 'opcao', label: 'Opção', type: 'select', options: ['OPTO pelo recebimento do Vale-Transporte', 'NÃO OPTO pelo recebimento do Vale-Transporte'], default: 'OPTO pelo recebimento do Vale-Transporte'},
      {key: 'linha1', label: 'Linha/Transporte 1', type: 'text', default: ''},
      {key: 'valor1', label: 'Valor Diário 1', type: 'text', default: ''},
      {key: 'linha2', label: 'Linha/Transporte 2', type: 'text', default: ''},
      {key: 'valor2', label: 'Valor Diário 2', type: 'text', default: ''},
    ],
    body: [
      'Eu, {{nome}}, CPF {{cpf}}, admitido(a) na empresa ' + EMPRESA.nome + ' em {{dataAdmissao}}, para exercer a função de {{cargo}}, residente à {{endereco}}, {{numero}}, {{bairro}}, {{cidade}}/{{estado}}, declaro que:',
      '',
      '> [[opcao]]',
      '',
      'Para deslocamento residência-trabalho-residência, utilizo o(s) seguinte(s) meio(s) de transporte:',
      '',
      '1. Linha/Transporte: [[linha1]] — Valor diário: R$ [[valor1]]',
      '2. Linha/Transporte: [[linha2]] — Valor diário: R$ [[valor2]]',
      '',
      'Declaro estar ciente de que o benefício do Vale-Transporte será custeado pelo empregado na parcela equivalente a 6% (seis por cento) de seu salário, e que a declaração falsa ou o uso indevido do benefício constitui falta grave.',
      '[DATE_LINE]',
      '[SIGNATURES:2]',
    ]
  },
  {
    id: 'declaracao-dependentes',
    title: 'DECLARAÇÃO DE DEPENDENTES PARA IR E SALÁRIO-FAMÍLIA',
    category: 'admissao',
    categoryLabel: 'Admissão',
    icon: '📋',
    customFields: [
      {key: 'dependentes_lista', label: 'Lista de Dependentes (Nome — Parentesco — Nascimento — CPF, um por linha)', type: 'textarea', default: ''},
    ],
    body: [
      'Eu, {{nome}}, CPF {{cpf}}, admitido(a) na empresa ' + EMPRESA.nome + ' no cargo de {{cargo}}, declaro para os devidos fins que possuo os seguintes dependentes:',
      '',
      '# DEPENDENTES',
      '[[dependentes_lista]]',
      '',
      'Declaro, sob as penas da lei, que as informações acima são verdadeiras e me comprometo a comunicar qualquer alteração à empresa.',
      '[DATE_LINE]',
      '[SIGNATURES:2]',
    ]
  },
  {
    id: 'autorizacao-desconto',
    title: 'AUTORIZAÇÃO DE DESCONTO EM FOLHA DE PAGAMENTO',
    category: 'admissao',
    categoryLabel: 'Admissão',
    icon: '📋',
    customFields: [
      {key: 'descontos', label: 'Descontos autorizados (ex: Vale-transporte 6%, Vale-refeição, etc.)', type: 'textarea', default: 'Vale-Transporte (6% do salário)\nContribuição Sindical\nPlano de Saúde (se aplicável)'},
    ],
    body: [
      'Eu, {{nome}}, CPF {{cpf}}, funcionário(a) da empresa ' + EMPRESA.nome + ', no cargo de {{cargo}}, AUTORIZO expressamente o desconto em minha folha de pagamento dos seguintes valores:',
      '',
      '[[descontos]]',
      '',
      'Estou ciente de que os descontos acima são previstos em lei ou decorrentes de benefícios por mim solicitados.',
      '[DATE_LINE]',
      '[SIGNATURES:2]',
    ]
  },
  // ═══ CONTROLE DE PONTO ═══
  {
    id: 'folha-ponto',
    title: 'FOLHA DE PONTO MENSAL',
    category: 'ponto',
    categoryLabel: 'Controle de Ponto',
    icon: '⏰',
    customFields: [
      {key: 'mes_ref', label: 'Mês de Referência', type: 'text', default: ''},
      {key: 'ano_ref', label: 'Ano de Referência', type: 'text', default: '2026'},
    ],
    body: [
      'Funcionário(a): {{nome}} | Cargo: {{cargo}}',
      'Departamento: {{departamento}} | Mês/Ano: [[mes_ref]]/[[ano_ref]]',
      '---',
      '[PONTO_TABLE]',
      '---',
      'Observações: _______________________________________________',
      '[DATE_LINE]',
      '[SIGNATURES:2]',
    ]
  },
  {
    id: 'ponto-diario',
    title: 'CONTROLE DE PONTO INDIVIDUAL DIÁRIO',
    category: 'ponto',
    categoryLabel: 'Controle de Ponto',
    icon: '⏰',
    customFields: [
      {key: 'data_ponto', label: 'Data', type: 'text', default: ''},
      {key: 'entrada', label: 'Horário de Entrada', type: 'text', default: ''},
      {key: 'saida_almoco', label: 'Saída para Almoço', type: 'text', default: ''},
      {key: 'retorno_almoco', label: 'Retorno do Almoço', type: 'text', default: ''},
      {key: 'saida', label: 'Horário de Saída', type: 'text', default: ''},
    ],
    body: [
      'Funcionário(a): {{nome}} | CPF: {{cpf}}',
      'Cargo: {{cargo}} | Departamento: {{departamento}}',
      '---',
      'Data: [[data_ponto]]',
      '',
      'Entrada: [[entrada]]',
      'Saída para Almoço: [[saida_almoco]]',
      'Retorno do Almoço: [[retorno_almoco]]',
      'Saída: [[saida]]',
      '',
      'Observações: _______________________________________________',
      '[SIGNATURES:2]',
    ]
  },
  // ═══ UNIFORMES E EPI ═══
  {
    id: 'entrega-uniforme',
    title: 'COMPROVANTE DE ENTREGA DE UNIFORME',
    category: 'uniforme',
    categoryLabel: 'Uniformes e EPI',
    icon: '👔',
    customFields: [
      {key: 'itens_uniforme', label: 'Itens entregues (ex: 2 camisetas, 2 calças, 1 avental, 1 par de sapatos)', type: 'textarea', default: ''},
      {key: 'tamanho', label: 'Tamanho', type: 'text', default: ''},
    ],
    body: [
      'Declaro ter recebido da empresa ' + EMPRESA.nome + ' os uniformes abaixo discriminados, para uso exclusivo durante a jornada de trabalho:',
      '---',
      'Funcionário(a): {{nome}} | CPF: {{cpf}}',
      'Cargo: {{cargo}} | Departamento: {{departamento}}',
      'Tamanho: [[tamanho]]',
      '---',
      '# ITENS ENTREGUES',
      '[[itens_uniforme]]',
      '---',
      'Comprometo-me a: utilizar o uniforme exclusivamente durante o expediente de trabalho; zelar pela conservação e higiene das peças; devolver os uniformes em caso de desligamento da empresa; comunicar a necessidade de reposição.',
      '[DATE_LINE]',
      '[SIGNATURES:2]',
    ]
  },
  {
    id: 'entrega-epi',
    title: 'COMPROVANTE DE ENTREGA DE EPI',
    category: 'uniforme',
    categoryLabel: 'Uniformes e EPI',
    icon: '👔',
    customFields: [
      {key: 'itens_epi', label: 'EPIs entregues (ex: Touca descartável, Avental impermeável, Luvas, Botas antiderrapantes)', type: 'textarea', default: ''},
      {key: 'ca_numeros', label: 'Certificados de Aprovação (CA) dos EPIs', type: 'text', default: ''},
    ],
    body: [
      'Declaro ter recebido da empresa ' + EMPRESA.nome + ' os Equipamentos de Proteção Individual (EPIs) abaixo relacionados, conforme determina a NR-6 do MTE:',
      '---',
      'Funcionário(a): {{nome}} | CPF: {{cpf}}',
      'Cargo: {{cargo}} | Departamento: {{departamento}}',
      '---',
      '# EQUIPAMENTOS ENTREGUES',
      '[[itens_epi]]',
      '',
      'Certificados de Aprovação: [[ca_numeros]]',
      '---',
      'Declaro que recebi os EPIs acima, fui orientado(a) sobre seu uso correto e me comprometo a: utilizá-los durante toda a jornada de trabalho; guardar e conservar os EPIs; comunicar qualquer dano ou necessidade de substituição; devolver os EPIs ao término do contrato de trabalho. Estou ciente de que o uso é obrigatório e que a recusa injustificada constitui falta grave.',
      '[DATE_LINE]',
      '[SIGNATURES:2]',
    ]
  },
  // ═══ DISCIPLINA ═══
  {
    id: 'advertencia',
    title: 'ADVERTÊNCIA ESCRITA',
    category: 'disciplina',
    categoryLabel: 'Disciplina',
    icon: '⚠️',
    customFields: [
      {key: 'data_ocorrencia', label: 'Data da Ocorrência', type: 'text', default: ''},
      {key: 'motivo', label: 'Motivo/Descrição da Falta', type: 'textarea', default: ''},
      {key: 'artigo_clt', label: 'Base Legal (Art. CLT)', type: 'text', default: 'Art. 482 da CLT'},
    ],
    body: [
      'A empresa ' + EMPRESA.nome + ', CNPJ ' + EMPRESA.cnpj + ', com sede na ' + EMPRESA.endereco + ', ' + EMPRESA.cidade + '/' + EMPRESA.uf + ', vem pela presente ADVERTIR o(a) funcionário(a):',
      '---',
      'Nome: {{nome}}',
      'CPF: {{cpf}}',
      'Cargo: {{cargo}} | Departamento: {{departamento}}',
      'Data de Admissão: {{dataAdmissao}}',
      '---',
      '# MOTIVO DA ADVERTÊNCIA',
      '[[motivo]]',
      '',
      'Data da ocorrência: [[data_ocorrencia]]',
      'Fundamentação legal: [[artigo_clt]]',
      '---',
      'Fica o(a) funcionário(a) ADVERTIDO(A) de que a reincidência poderá acarretar penalidades mais severas, podendo resultar em suspensão e/ou demissão por justa causa, nos termos da legislação trabalhista vigente.',
      '',
      'O(A) funcionário(a) declara ter tomado ciência desta advertência.',
      '[DATE_LINE]',
      '[SIGNATURES:4]',
    ]
  },
  {
    id: 'suspensao',
    title: 'SUSPENSÃO DISCIPLINAR',
    category: 'disciplina',
    categoryLabel: 'Disciplina',
    icon: '⚠️',
    customFields: [
      {key: 'dias_suspensao', label: 'Quantidade de Dias de Suspensão', type: 'text', default: ''},
      {key: 'data_inicio', label: 'Data de Início da Suspensão', type: 'text', default: ''},
      {key: 'data_retorno', label: 'Data de Retorno', type: 'text', default: ''},
      {key: 'motivo', label: 'Motivo da Suspensão', type: 'textarea', default: ''},
    ],
    body: [
      'A empresa ' + EMPRESA.nome + ', CNPJ ' + EMPRESA.cnpj + ', vem pela presente SUSPENDER o(a) funcionário(a):',
      '---',
      'Nome: {{nome}} | CPF: {{cpf}}',
      'Cargo: {{cargo}} | Departamento: {{departamento}}',
      'Data de Admissão: {{dataAdmissao}}',
      '---',
      '# SUSPENSÃO DISCIPLINAR',
      'Quantidade de dias: [[dias_suspensao]] dia(s)',
      'Período: de [[data_inicio]] a [[data_retorno]]',
      '',
      '# MOTIVO',
      '[[motivo]]',
      '---',
      'Durante o período de suspensão, o(a) funcionário(a) não deverá comparecer ao trabalho, ficando sem remuneração nos dias correspondentes. O(A) funcionário(a) fica ciente de que novas infrações poderão resultar em demissão por justa causa.',
      '[DATE_LINE]',
      '[SIGNATURES:4]',
    ]
  },
  {
    id: 'abandono-emprego',
    title: 'TERMO DE ABANDONO DE EMPREGO',
    category: 'disciplina',
    categoryLabel: 'Disciplina',
    icon: '⚠️',
    customFields: [
      {key: 'data_ultima_presenca', label: 'Data da Última Presença', type: 'text', default: ''},
      {key: 'dias_ausencia', label: 'Dias Consecutivos de Ausência', type: 'text', default: '30'},
      {key: 'notificacoes', label: 'Notificações enviadas (datas e meios)', type: 'textarea', default: ''},
    ],
    body: [
      'A empresa ' + EMPRESA.nome + ', CNPJ ' + EMPRESA.cnpj + ', vem pelo presente REGISTRAR o abandono de emprego por parte do(a) funcionário(a):',
      '---',
      'Nome: {{nome}} | CPF: {{cpf}}',
      'Cargo: {{cargo}} | Data de Admissão: {{dataAdmissao}}',
      '---',
      'O(A) referido(a) funcionário(a) encontra-se ausente de suas funções desde [[data_ultima_presenca]], totalizando [[dias_ausencia]] dias consecutivos de ausência injustificada, configurando abandono de emprego nos termos do Art. 482, alínea "i", da CLT.',
      '',
      '# NOTIFICAÇÕES REALIZADAS',
      '[[notificacoes]]',
      '',
      'Diante do exposto, fica caracterizado o abandono de emprego, ensejando a rescisão do contrato de trabalho por justa causa.',
      '[DATE_LINE]',
      '[SIGNATURES:3]',
    ]
  },
  // ═══ FÉRIAS ═══
  {
    id: 'aviso-ferias',
    title: 'AVISO DE FÉRIAS',
    category: 'ferias',
    categoryLabel: 'Férias',
    icon: '🏖️',
    customFields: [
      {key: 'periodo_aquisitivo', label: 'Período Aquisitivo (ex: 01/03/2025 a 28/02/2026)', type: 'text', default: ''},
      {key: 'data_inicio_ferias', label: 'Data de Início das Férias', type: 'text', default: ''},
      {key: 'data_fim_ferias', label: 'Data de Fim das Férias', type: 'text', default: ''},
      {key: 'dias_ferias', label: 'Quantidade de Dias', type: 'text', default: '30'},
      {key: 'data_retorno', label: 'Data de Retorno ao Trabalho', type: 'text', default: ''},
    ],
    body: [
      'A empresa ' + EMPRESA.nome + ' comunica ao(à) funcionário(a) abaixo que lhe serão concedidas férias conforme segue:',
      '---',
      'Nome: {{nome}} | CPF: {{cpf}}',
      'Cargo: {{cargo}} | Departamento: {{departamento}}',
      '---',
      'Período aquisitivo: [[periodo_aquisitivo]]',
      'Dias de férias: [[dias_ferias]] dias',
      'Início das férias: [[data_inicio_ferias]]',
      'Término das férias: [[data_fim_ferias]]',
      'Data de retorno: [[data_retorno]]',
      '',
      'O pagamento das férias será efetuado conforme Art. 145 da CLT, até 2 (dois) dias antes do início do período de gozo.',
      '[DATE_LINE]',
      '[SIGNATURES:2]',
    ]
  },
  {
    id: 'recibo-ferias',
    title: 'RECIBO DE FÉRIAS',
    category: 'ferias',
    categoryLabel: 'Férias',
    icon: '🏖️',
    customFields: [
      {key: 'periodo_aquisitivo', label: 'Período Aquisitivo', type: 'text', default: ''},
      {key: 'dias_ferias', label: 'Dias de Férias', type: 'text', default: '30'},
      {key: 'valor_ferias', label: 'Valor das Férias (R$)', type: 'text', default: ''},
      {key: 'valor_terco', label: 'Valor do 1/3 Constitucional (R$)', type: 'text', default: ''},
      {key: 'descontos', label: 'Descontos (INSS, IR, etc.)', type: 'text', default: ''},
      {key: 'valor_liquido', label: 'Valor Líquido (R$)', type: 'text', default: ''},
    ],
    body: [
      'Nome: {{nome}} | CPF: {{cpf}}',
      'Cargo: {{cargo}} | Admissão: {{dataAdmissao}}',
      '---',
      'Período aquisitivo: [[periodo_aquisitivo]]',
      'Dias de férias: [[dias_ferias]]',
      '',
      '# VALORES',
      'Férias: R$ [[valor_ferias]]',
      '1/3 Constitucional: R$ [[valor_terco]]',
      'Descontos: R$ [[descontos]]',
      '---',
      '> VALOR LÍQUIDO: R$ [[valor_liquido]]',
      '---',
      'Declaro ter recebido a importância líquida acima descrita, referente às férias do período mencionado.',
      '[DATE_LINE]',
      '[SIGNATURES:2]',
    ]
  },
  {
    id: 'abono-ferias',
    title: 'SOLICITAÇÃO DE ABONO PECUNIÁRIO DE FÉRIAS',
    category: 'ferias',
    categoryLabel: 'Férias',
    icon: '🏖️',
    customFields: [
      {key: 'periodo_aquisitivo', label: 'Período Aquisitivo', type: 'text', default: ''},
    ],
    body: [
      'Eu, {{nome}}, CPF {{cpf}}, funcionário(a) da empresa ' + EMPRESA.nome + ', no cargo de {{cargo}}, venho por meio desta SOLICITAR a conversão de 1/3 (um terço) das férias em abono pecuniário, conforme previsto no Art. 143 da CLT.',
      '',
      'Período aquisitivo: [[periodo_aquisitivo]]',
      '',
      'Solicito que 10 (dez) dias de minhas férias sejam convertidos em abono pecuniário.',
      '[DATE_LINE]',
      '[SIGNATURES:2]',
    ]
  },
  // ═══ DECLARAÇÕES ═══
  {
    id: 'declaracao-vinculo',
    title: 'DECLARAÇÃO DE VÍNCULO EMPREGATÍCIO',
    category: 'declaracoes',
    categoryLabel: 'Declarações',
    icon: '📄',
    customFields: [
      {key: 'finalidade', label: 'Finalidade da Declaração', type: 'text', default: 'para os devidos fins'},
    ],
    body: [
      'DECLARAMOS, [[finalidade]], que o(a) Sr(a). {{nome}}, portador(a) do CPF {{cpf}} e RG {{rg}}, é funcionário(a) desta empresa desde {{dataAdmissao}}, exercendo a função de {{cargo}}, com remuneração mensal de R$ {{salario}}.',
      '',
      'A presente declaração é expedida por solicitação do(a) próprio(a) interessado(a) e não gera qualquer compromisso ou responsabilidade por parte da empresa.',
      '[DATE_LINE]',
      '[SIGNATURES:1]',
    ]
  },
  {
    id: 'declaracao-conta',
    title: 'DECLARAÇÃO PARA ABERTURA DE CONTA BANCÁRIA',
    category: 'declaracoes',
    categoryLabel: 'Declarações',
    icon: '📄',
    customFields: [
      {key: 'banco_destino', label: 'Banco para Abertura de Conta', type: 'text', default: ''},
    ],
    body: [
      'DECLARAMOS, para fins de abertura de conta bancária junto ao [[banco_destino]], que o(a) Sr(a). {{nome}}, portador(a) do CPF {{cpf}} e RG {{rg}}, é funcionário(a) desta empresa desde {{dataAdmissao}}, exercendo a função de {{cargo}}, percebendo remuneração mensal de R$ {{salario}}.',
      '',
      'A presente declaração é expedida por solicitação do(a) próprio(a) interessado(a).',
      '[DATE_LINE]',
      '[SIGNATURES:1]',
    ]
  },
  // ═══ ESPECÍFICO PADARIA ═══
  {
    id: 'normas-higiene',
    title: 'TERMO DE CIÊNCIA DAS NORMAS DE HIGIENE E MANIPULAÇÃO DE ALIMENTOS',
    category: 'padaria',
    categoryLabel: 'Específico Padaria',
    icon: '🍞',
    customFields: [],
    body: [
      'Eu, {{nome}}, CPF {{cpf}}, admitido(a) na empresa ' + EMPRESA.nome + ' no cargo de {{cargo}}, DECLARO ter recebido treinamento e orientação sobre as normas de higiene e manipulação de alimentos, conforme a RDC 216 da ANVISA, e me comprometo a:',
      '',
      '• Lavar as mãos frequentemente, especialmente antes de manipular alimentos;',
      '• Utilizar os EPIs fornecidos (touca, avental, luvas, botas) durante toda a jornada;',
      '• Manter unhas curtas, limpas e sem esmalte durante o trabalho;',
      '• Não utilizar adornos (brincos, anéis, pulseiras, relógios) na área de produção;',
      '• Manter os uniformes limpos e em bom estado de conservação;',
      '• Comunicar qualquer problema de saúde que possa contaminar os alimentos;',
      '• Não fumar, comer ou beber nas áreas de produção;',
      '• Seguir os Procedimentos Operacionais Padronizados (POPs) da empresa;',
      '• Armazenar corretamente matérias-primas e produtos acabados;',
      '• Manter o ambiente de trabalho limpo e organizado.',
      '',
      'Declaro estar ciente de que o descumprimento destas normas poderá resultar em sanções disciplinares e que é minha responsabilidade zelar pela qualidade e segurança dos alimentos produzidos.',
      '[DATE_LINE]',
      '[SIGNATURES:2]',
    ]
  },
  {
    id: 'exame-saude',
    title: 'COMPROVANTE DE EXAME DE SAÚDE OCUPACIONAL',
    category: 'padaria',
    categoryLabel: 'Específico Padaria',
    icon: '🍞',
    customFields: [
      {key: 'tipo_exame', label: 'Tipo de Exame', type: 'select', options: ['Admissional', 'Periódico', 'Demissional', 'Retorno ao Trabalho', 'Mudança de Função'], default: 'Admissional'},
      {key: 'data_exame', label: 'Data do Exame', type: 'text', default: ''},
      {key: 'resultado', label: 'Resultado', type: 'select', options: ['Apto', 'Inapto', 'Apto com Restrições'], default: 'Apto'},
      {key: 'medico', label: 'Médico Responsável', type: 'text', default: ''},
      {key: 'crm', label: 'CRM do Médico', type: 'text', default: ''},
      {key: 'proxima_data', label: 'Data do Próximo Exame', type: 'text', default: ''},
    ],
    body: [
      'Nome: {{nome}} | CPF: {{cpf}}',
      'Cargo: {{cargo}} | Departamento: {{departamento}}',
      '---',
      '# EXAME DE SAÚDE OCUPACIONAL',
      'Tipo: [[tipo_exame]]',
      'Data do Exame: [[data_exame]]',
      'Resultado: [[resultado]]',
      '',
      'Médico Responsável: [[medico]]',
      'CRM: [[crm]]',
      '',
      'Próximo exame periódico: [[proxima_data]]',
      '[DATE_LINE]',
      '[SIGNATURES:2]',
    ]
  },
  {
    id: 'termo-adornos',
    title: 'TERMO DE RESPONSABILIDADE SOBRE USO DE ADORNOS',
    category: 'padaria',
    categoryLabel: 'Específico Padaria',
    icon: '🍞',
    customFields: [],
    body: [
      'Eu, {{nome}}, CPF {{cpf}}, funcionário(a) da empresa ' + EMPRESA.nome + ', no cargo de {{cargo}}, DECLARO estar ciente de que, conforme a RDC 216 da ANVISA e as normas internas da empresa:',
      '',
      'É PROIBIDO o uso dos seguintes adornos durante a jornada de trabalho nas áreas de produção e manipulação de alimentos:',
      '',
      '• Brincos, alianças, anéis e pulseiras;',
      '• Relógios e correntes;',
      '• Piercings visíveis;',
      '• Cílios postiços e esmaltes (inclusive base);',
      '• Maquiagem em excesso.',
      '',
      'Comprometo-me a cumprir estas determinações, ciente de que o descumprimento constitui infração às normas de segurança alimentar e pode resultar em sanções disciplinares.',
      '[DATE_LINE]',
      '[SIGNATURES:2]',
    ]
  },
  // ═══ SAÚDE ═══
  {
    id: 'inclusao-plano-saude',
    title: 'SOLICITAÇÃO DE INCLUSÃO EM PLANO DE SAÚDE',
    category: 'saude',
    categoryLabel: 'Saúde',
    icon: '🏥',
    customFields: [
      {key: 'operadora', label: 'Operadora do Plano', type: 'text', default: ''},
      {key: 'plano', label: 'Tipo do Plano', type: 'text', default: ''},
      {key: 'dependentes_plano', label: 'Dependentes a incluir (Nome — Parentesco — Nascimento — CPF)', type: 'textarea', default: ''},
    ],
    body: [
      'Solicito a inclusão no plano de saúde oferecido pela empresa ' + EMPRESA.nome + ', conforme dados abaixo:',
      '---',
      'Nome: {{nome}} | CPF: {{cpf}}',
      'Data de Nascimento: {{dataNascimento}}',
      'Cargo: {{cargo}} | Admissão: {{dataAdmissao}}',
      '---',
      'Operadora: [[operadora]]',
      'Plano: [[plano]]',
      '',
      '# DEPENDENTES A INCLUIR',
      '[[dependentes_plano]]',
      '',
      'Autorizo o desconto em folha de pagamento da minha parte na mensalidade do plano.',
      '[DATE_LINE]',
      '[SIGNATURES:2]',
    ]
  },
  {
    id: 'exclusao-plano-saude',
    title: 'SOLICITAÇÃO DE EXCLUSÃO DE PLANO DE SAÚDE',
    category: 'saude',
    categoryLabel: 'Saúde',
    icon: '🏥',
    customFields: [
      {key: 'motivo_exclusao', label: 'Motivo da Exclusão', type: 'textarea', default: ''},
      {key: 'excluir_quem', label: 'Quem será excluído (Titular, dependente, todos)', type: 'text', default: ''},
    ],
    body: [
      'Solicito a exclusão do plano de saúde oferecido pela empresa ' + EMPRESA.nome + ', conforme abaixo:',
      '---',
      'Nome: {{nome}} | CPF: {{cpf}}',
      'Cargo: {{cargo}}',
      '---',
      'Excluir: [[excluir_quem]]',
      'Motivo: [[motivo_exclusao]]',
      '',
      'Estou ciente de que a exclusão será processada conforme prazos da operadora e legislação vigente.',
      '[DATE_LINE]',
      '[SIGNATURES:2]',
    ]
  },
  // ═══ DESLIGAMENTO ═══
  {
    id: 'aviso-previo',
    title: 'AVISO PRÉVIO',
    category: 'desligamento',
    categoryLabel: 'Desligamento',
    icon: '🚪',
    customFields: [
      {key: 'tipo_aviso', label: 'Tipo do Aviso', type: 'select', options: ['Trabalhado (30 dias)', 'Indenizado'], default: 'Trabalhado (30 dias)'},
      {key: 'iniciativa', label: 'De quem é a iniciativa', type: 'select', options: ['Do empregador', 'Do empregado'], default: 'Do empregador'},
      {key: 'data_aviso', label: 'Data do Aviso', type: 'text', default: ''},
      {key: 'ultimo_dia', label: 'Último Dia de Trabalho', type: 'text', default: ''},
    ],
    body: [
      'A empresa ' + EMPRESA.nome + ', CNPJ ' + EMPRESA.cnpj + ', comunica ao(à) funcionário(a) abaixo identificado(a) a concessão de AVISO PRÉVIO:',
      '---',
      'Nome: {{nome}} | CPF: {{cpf}}',
      'Cargo: {{cargo}} | Admissão: {{dataAdmissao}}',
      '---',
      'Tipo: [[tipo_aviso]]',
      'Iniciativa: [[iniciativa]]',
      'Data do aviso: [[data_aviso]]',
      'Último dia de trabalho: [[ultimo_dia]]',
      '',
      'O(A) funcionário(a) declara estar ciente dos termos deste aviso prévio e de seus direitos conforme a legislação trabalhista vigente.',
      '[DATE_LINE]',
      '[SIGNATURES:2]',
    ]
  },
  {
    id: 'termo-rescisao',
    title: 'TERMO DE RESCISÃO DO CONTRATO DE TRABALHO',
    category: 'desligamento',
    categoryLabel: 'Desligamento',
    icon: '🚪',
    customFields: [
      {key: 'motivo_rescisao', label: 'Motivo da Rescisão', type: 'select', options: ['Dispensa sem justa causa', 'Dispensa com justa causa', 'Pedido de demissão', 'Término de contrato', 'Acordo entre as partes'], default: 'Dispensa sem justa causa'},
      {key: 'data_desligamento', label: 'Data do Desligamento', type: 'text', default: ''},
      {key: 'saldo_salario', label: 'Saldo de Salário (R$)', type: 'text', default: ''},
      {key: 'ferias_proporcionais', label: 'Férias Proporcionais + 1/3 (R$)', type: 'text', default: ''},
      {key: 'decimo_terceiro', label: '13º Proporcional (R$)', type: 'text', default: ''},
      {key: 'aviso_previo_valor', label: 'Aviso Prévio (R$)', type: 'text', default: ''},
      {key: 'total_bruto', label: 'Total Bruto (R$)', type: 'text', default: ''},
      {key: 'descontos_rescisao', label: 'Total de Descontos (R$)', type: 'text', default: ''},
      {key: 'total_liquido', label: 'Total Líquido (R$)', type: 'text', default: ''},
    ],
    body: [
      '# DADOS DO EMPREGADOR',
      EMPRESA.nome,
      'CNPJ: ' + EMPRESA.cnpj + ' | ' + EMPRESA.endereco,
      '---',
      '# DADOS DO EMPREGADO',
      'Nome: {{nome}} | CPF: {{cpf}} | RG: {{rg}}',
      'Cargo: {{cargo}} | Admissão: {{dataAdmissao}}',
      '---',
      'Motivo da Rescisão: [[motivo_rescisao]]',
      'Data do Desligamento: [[data_desligamento]]',
      '---',
      '# VALORES DA RESCISÃO',
      'Saldo de Salário: R$ [[saldo_salario]]',
      'Férias Proporcionais + 1/3: R$ [[ferias_proporcionais]]',
      '13º Proporcional: R$ [[decimo_terceiro]]',
      'Aviso Prévio: R$ [[aviso_previo_valor]]',
      '---',
      '> Total Bruto: R$ [[total_bruto]]',
      '> Descontos: R$ [[descontos_rescisao]]',
      '> TOTAL LÍQUIDO: R$ [[total_liquido]]',
      '---',
      'As partes declaram que foram quitadas todas as verbas rescisórias devidas.',
      '[DATE_LINE]',
      '[SIGNATURES:2]',
    ]
  },
  {
    id: 'quitacao-verbas',
    title: 'TERMO DE QUITAÇÃO DE VERBAS RESCISÓRIAS',
    category: 'desligamento',
    categoryLabel: 'Desligamento',
    icon: '🚪',
    customFields: [
      {key: 'data_desligamento', label: 'Data do Desligamento', type: 'text', default: ''},
      {key: 'valor_total', label: 'Valor Total Recebido (R$)', type: 'text', default: ''},
    ],
    body: [
      'Eu, {{nome}}, CPF {{cpf}}, ex-funcionário(a) da empresa ' + EMPRESA.nome + ', onde exerci a função de {{cargo}} desde {{dataAdmissao}} até [[data_desligamento]], DECLARO ter recebido a importância de R$ [[valor_total]] referente às verbas rescisórias devidas pela empresa.',
      '',
      'Declaro, para todos os efeitos legais, que não tenho mais nada a reclamar da referida empresa em relação ao contrato de trabalho mantido entre as partes, dando plena e irrevogável quitação.',
      '[DATE_LINE]',
      '[SIGNATURES:3]',
    ]
  },
  {
    id: 'devolucao-uniforme',
    title: 'COMPROVANTE DE DEVOLUÇÃO DE UNIFORME/EPI',
    category: 'desligamento',
    categoryLabel: 'Desligamento',
    icon: '🚪',
    customFields: [
      {key: 'itens_devolvidos', label: 'Itens Devolvidos', type: 'textarea', default: ''},
      {key: 'estado_conservacao', label: 'Estado de Conservação', type: 'select', options: ['Bom', 'Regular', 'Ruim'], default: 'Bom'},
    ],
    body: [
      'Declaro que o(a) funcionário(a) abaixo identificado(a) devolveu os uniformes e/ou EPIs listados:',
      '---',
      'Nome: {{nome}} | CPF: {{cpf}}',
      'Cargo: {{cargo}}',
      '---',
      '# ITENS DEVOLVIDOS',
      '[[itens_devolvidos]]',
      '',
      'Estado de conservação: [[estado_conservacao]]',
      '',
      'A empresa declara o recebimento dos itens acima.',
      '[DATE_LINE]',
      '[SIGNATURES:2]',
    ]
  },
];

module.exports = { EMPRESA, TEMPLATES, getLogoBase64 };
